# Generated by Django 4.0.3 on 2022-03-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmail',
            name='name',
            field=models.EmailField(max_length=254, null=True, verbose_name='mail'),
        ),
    ]
